# Numpy

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
print(type(lst))
lst.ndim

<class 'list'>

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
arr=np.array([11,22,33,44,55])
arr

In [ ]:
print(type(arr))

In [ ]:
arr.ndim

# Difference between array and list

# diff 1

In [ ]:
lst=[1,"satish",True,2.8]
lst

In [ ]:
arr=np.array([1,2,3,4,5])
arr

In [ ]:
arr=np.array([1,"satish",4.6])
arr

# diff 2

In [ ]:
lst=[1,2,3,4,5]
lst

In [ ]:
lst=[1,2,3,4,5]*5
lst

In [ ]:
lst=[1,2,3,4,5]

In [ ]:
l=[]
for i in lst:
    i=i*5
    l.append(i)
print(l)

In [ ]:
arr=np.array([1,2,3,4,5])
arr

In [ ]:
arr=np.array([1,2,3,4,5])*5
print(arr)

In [ ]:
arr=np.array([1,2,3,4,5])+5
print(arr)

# diff 3

In [ ]:
[ i for i in range(1,6)]

In [ ]:
[ i**2 for i in range(1,6)]

In [ ]:
%timeit [ i**2 for i in range(1,6)]

In [ ]:
%timeitnp.arange(1,6)**2

In [ ]:
%timeit [ i**2 for i in range(1,600)]

In [ ]:
%timeit np.arange(1,600)**2

# 1D,2D and 3D Array

# 1D Array

In [ ]:
arr=np.array([1,2,3,4,5])
arr

In [ ]:
arr.shape

In [ ]:
arr.ndim

# 2D Array

In [ ]:
arr1=np.array([[1,2,3,4,5]])
print(arr1)

In [ ]:
arr1.shape

In [ ]:
arr1.ndim

In [ ]:
arr2=np.array([[1,2,3],[44,55,66]])
print(arr2)

# 3D Array

In [ ]:
arr3=np.array([[[1,2,3,4,5]]])
print(arr3)

In [ ]:
arr3.ndim

In [ ]:
arr3.shape

In [ ]:
arr=np.array([[[1,2],[34,67]],[[4,5],[21,34]],[[66,88],[31,67]]])
arr

In [ ]:
arr.shape

In [ ]:
arr=np.array([1,2,3,4,5],ndmin=10)

In [ ]:
print(arr)

In [ ]:
arr.shape

In [ ]:
arr=np.array([1,2,3,4,5],ndmin=32)
print(arr)

# Special Numpy Function

In [ ]:
np.zeros(5)

In [ ]:
np.zeros([5,4],dtype=int)

In [ ]:
np.zeros([2,3,4],dtype=int)

In [ ]:
np.ones(5,dtype=int)

In [ ]:
np.ones([2,3],dtype=int)

In [ ]:
np.ones([1,2,3],dtype=int)

In [ ]:
np.full(5,2)

In [ ]:
np.full([2,3],5)

In [ ]:
np.full([2,3],5.3)

In [ ]:
np.full([2,3],5.3,dtype=str)

In [ ]:
np.arange(1,11)

In [ ]:
np.arange(0,100,5)

# Pandas

In [6]:
import pandas as pd

In [ ]:
lst=[4,5,6,3,1]
lst

In [ ]:
ser=pd.Series(lst)
ser

In [ ]:
type(ser)

In [ ]:
ser=pd.Series([1,2,34,5,6],index=["a","b","c","d","e"])
ser

In [ ]:
ser=pd.Series([1,2,34,5,6],index=["a","b","c","d","e"],name="Rating")
ser

# Dataframe

__Using List__

In [ ]:
lst=[["apple",5],["mango",10],["banana",15]]
lst

In [ ]:
df=pd.DataFrame(lst)
df

In [ ]:
df=pd.DataFrame(lst,columns=["Fruits","Quantity"])
df

In [ ]:
lst=[["apple",5,"L"],["mango",10,"D"],["banana",15,"L"]]
df=pd.DataFrame(lst,columns=["Fruits","Quantity","L/D"])
df

In [ ]:
type(df)

In [ ]:
import numpy as np

In [ ]:
lst=[["apple",5,"L"],["mango",np.nan,"D"],["banana",15,"L"]]
df=pd.DataFrame(lst,columns=["Fruits","Quantity","L/D"])
df

__Using Dictionary__

In [ ]:
fruits={
    "fruits":["apple","banana","mango","orange"],
    "quantity":[12,15,16,10],
    "like/dislike":["L","D","L","D"]
}
df=pd.DataFrame(fruits)
df

In [ ]:
df.shape

In [ ]:
df.ndim

In [ ]:
df["fruits"]

In [ ]:
df.fruits

In [ ]:
df["fruits","like/dislike"]

In [ ]:
df[["fruits","like/dislike"]]

# Arithmatic Operation

In [ ]:
df=pd.DataFrame(
    {
        "A":[1,2,3,4,5],
        "B":[7,8,4,2,1]
    }
)
df

In [ ]:
df["A"]

In [ ]:
df["C"]=df["A"]+df["B"]

In [ ]:
df

In [ ]:
del df["c"]

In [ ]:
df

In [ ]:
df["D"]=df["A"]*df["B"]

In [ ]:
df

__Insert and delete__

In [ ]:
df.insert(0,"Alphabets",["a","b","c","d","e"])

In [ ]:
df

In [ ]:
d=df.copy()

In [ ]:
f=df

In [ ]:
print(d)
print()
print(f)

In [ ]:
del df["A"]

In [ ]:
df

In [ ]:
del df

In [ ]:
df

In [ ]:
df=d

In [ ]:
df

# Load the database

In [ ]:
df=pd.read_csv("petrol_consumption.csv")
df

__Basic Exploratory Data Analysis (EDA)__

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
# df.describe(include="object")

In [ ]:
df.head(4)

In [ ]:
df.tail()

__Indexing and Slicing__
- iloc[] and loc[]

In [ ]:
df.iloc[3]

In [ ]:
df.iloc[0:48,0:5]

In [ ]:
df.iloc[:,:]

In [ ]:
df.iloc[:5,:3]

In [ ]:
df.iloc[4:11,2:]

In [ ]:
df.iloc[4:11,:5:2]

In [ ]:
# loc[]

In [ ]:
df.loc[4:11,["Petrol_tax","Average_income","Petrol_Consumption"]]

In [ ]:
df[["Petrol_tax","Average_income","Petrol_Consumption"]][4:11]

In [ ]:
df[["Petrol_tax","Average_income","Petrol_Consumption"]].index

In [ ]:
df[df["Petrol_tax"]==9.00]

In [ ]:
df[df["Petrol_tax"]==9.00].index

__Unique Value Identification__
- nunique()
- unique()
- value_counts()

In [ ]:
df.nunique()

In [ ]:
df["Petrol_tax"].nunique()

In [ ]:
df["Petrol_tax"].unique()

In [ ]:
df["Petrol_tax"].value_counts()

In [ ]:
df["Petrol_tax"].mean()

In [ ]:
df["Petrol_tax"].median()

In [ ]:
df["Petrol_tax"].mode()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
sns.distplot(df["Petrol_tax"],bins=30,color="r",label=f"skewness : {round(df["Petrol_tax"].skew(),2)}")
plt.legend()
plt.show()

# Missing Data
- filna()
- dropna()

In [ ]:
df

In [ ]:
df.isnull()

In [ ]:
df.isnull().any()

In [ ]:
df.isnull().sum()

In [ ]:
df.isnull().mean()*100

In [ ]:
df.fillna(888888888)

In [ ]:
df["Average_income"].mean()

In [ ]:
df["Average_income"].median()

In [ ]:
sns.distplot(df["Average_income"],bins=30,color="k",label=f"skewness: {round(df["Average_income"].skew(),2)}")
plt.legend()
plt.show()

In [ ]:
df["Average_income"].fillna(df["Average_income"].mean())

In [ ]:
df["Average_income"].fillna(df["Average_income"].mean(),inplace=True)

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna()

In [ ]:
df.shape

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.shape

In [ ]:
df.isnull().sum()

In [ ]:
df.isna().sum()

# Duplicate Data

In [ ]:
df.duplicated().sum()

In [ ]:
df[df.duplicated()]

# Drop()

In [ ]:
df

In [ ]:
df.drop(columns=["Petrol_Consumption"],axis=1)

In [ ]:
df.drop(columns=["Petrol_Consumption"],axis=1,inplace=True)

In [ ]:
df

In [ ]:
df.drop(index=[0,1,2,3,4,5],axis=1) #drop() always delete the row regardless of axis

# Concat() and Merge()
- Concat()

In [ ]:
df1=pd.DataFrame({"A":[1,2,3,4,5],"B":[11,22,33,44,55]})
df2=pd.DataFrame({"C":[11,12,13,14,15],"D":[101,202,303,404,505]})

In [ ]:
print(df1)
print(df2)

In [ ]:
pd.concat([df1,df2])

In [ ]:
pd.concat([df1,df2],axis=0,ignore_index=True)

In [ ]:
pd.concat([df1,df2],axis=1)

# Merge()

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":[11,22,33]})
df2=pd.DataFrame({"A":[11,2,3],"C":[101,202,303]})

In [ ]:
df2.merge(df1,on="A")

# GroupBy() Function

In [7]:
data=pd.read_csv("emp_data.csv")

In [ ]:
data

In [ ]:
data.nunique()

In [ ]:
data["City"].unique()

In [ ]:
data["City"].value_counts()

In [ ]:
data.groupby("City")

In [ ]:
noida=data.groupby("City").get_group("Noida")
noida

In [ ]:
noida.shape

In [ ]:
noida["Salary"].min()

In [ ]:
noida[noida.Salary== 43908]

In [ ]:
noida["Salary"].max()

In [ ]:
noida["Salary"].mean()

In [ ]:
noida[noida.Salary<70728.9]

In [ ]:
len(noida[noida.Salary<70728.9])

In [ ]:
noida[noida.Salary<70728.9].Salary

In [ ]:
noida[noida.Salary<70728.9][["Emp_id","Salary"]].values

In [ ]:
noida[noida.Salary<70728.9]["Salary"].index

# Set_index() and Reset_index()

In [ ]:
data

In [ ]:
data.set_index("Emp_id",inplace=True)

In [ ]:
data

In [ ]:
data.reset_index(inplace=True)

In [ ]:
data

# sort_values()

In [ ]:
data

In [ ]:
data.sort_values("Salary")

In [ ]:
data.sort_values("Salary",ascending=False)

# Map() and apply()

In [ ]:
data["City"]

In [ ]:
data["City"]=data["City"].map({"Gurgaon":0,"Noida":1,"Pune":2,"Banglore":3})

In [ ]:
data

In [ ]:
data["Name"].dtype

In [ ]:
data["Name"].apply(lambda x: x.replace("_","-"))

In [ ]:
data["Updated_Name"]=data["Name"].apply(lambda x: x.replace("_","-"))

In [8]:
data

    Emp_id     Name      City  Salary
0        1    Emp_1     Noida   76252
1        2    Emp_2  Banglore   60315
2        3    Emp_3     Noida   73672
3        4    Emp_4      Pune   46501
4        5    Emp_5  Banglore   68611
..     ...      ...       ...     ...
95      96   Emp_96  Banglore   60006
96      97   Emp_97     Noida   60635
97      98   Emp_98   Gurgaon   51311
98      99   Emp_99      Pune   89409
99     100  Emp_100   Gurgaon   92971

[100 rows x 4 columns]

In [12]:
def INR_to_Dollar(Salary):
    dollar=[]
    for i in Salary:
        d=i/85.50
        dollar.append(f"{round(d,2)} USD")
    return dollar

In [13]:
INR_to_Dollar(data["Salary"])

['891.84 USD',
 '705.44 USD',
 '861.66 USD',
 '543.87 USD',
 '802.47 USD',
 '522.18 USD',
 '1115.88 USD',
 '890.89 USD',
 '1040.92 USD',
 '782.69 USD',
 '592.02 USD',
 '806.27 USD',
 '762.77 USD',
 '1082.35 USD',
 '643.08 USD',
 '963.67 USD',
 '887.49 USD',
 '731.63 USD',
 '513.54 USD',
 '1034.62 USD',
 '795.24 USD',
 '833.94 USD',
 '831.06 USD',
 '883.31 USD',
 '614.32 USD',
 '522.92 USD',
 '956.35 USD',
 '595.25 USD',
 '1082.14 USD',
 '1052.25 USD',
 '722.08 USD',
 '821.01 USD',
 '772.23 USD',
 '1132.7 USD',
 '820.32 USD',
 '1121.06 USD',
 '1152.49 USD',
 '585.65 USD',
 '649.13 USD',
 '567.71 USD',
 '914.88 USD',
 '931.73 USD',
 '1030.12 USD',
 '649.82 USD',
 '684.53 USD',
 '694.84 USD',
 '566.08 USD',
 '538.5 USD',
 '760.05 USD',
 '612.04 USD',
 '581.61 USD',
 '834.33 USD',
 '663.09 USD',
 '616.18 USD',
 '818.22 USD',
 '570.82 USD',
 '912.16 USD',
 '1057.6 USD',
 '1041.61 USD',
 '526.36 USD',
 '1009.52 USD',
 '1012.67 USD',
 '1053.6 USD',
 '728.7 USD',
 '536.9 USD',
 '928.16 USD',
 '565.87 USD',
 '911.25 USD',
 '648.62 USD',
 '573.13 USD',
 '536.25 USD',
 '537.36 USD',
 '551.39 USD',
 '617.85 USD',
 '1013.37 USD',
 '538.18 USD',
 '563.65 USD',
 '1096.92 USD',
 '1085.89 USD',
 '682.7 USD',
 '558.2 USD',
 '678.14 USD',
 '866.2 USD',
 '536.8 USD',
 '606.32 USD',
 '875.16 USD',
 '621.35 USD',
 '1071.18 USD',
 '513.25 USD',
 '850.61 USD',
 '803.91 USD',
 '610.94 USD',
 '549.72 USD',
 '1057.89 USD',
 '1032.92 USD',
 '701.82 USD',
 '709.18 USD',
 '600.13 USD',
 '1045.72 USD',
 '1087.38 USD']

In [14]:
data["Salary_in_$"]=INR_to_Dollar(data["Salary"])

In [15]:
data

    Emp_id     Name      City  Salary  Salary_in_$
0        1    Emp_1     Noida   76252   891.84 USD
1        2    Emp_2  Banglore   60315   705.44 USD
2        3    Emp_3     Noida   73672   861.66 USD
3        4    Emp_4      Pune   46501   543.87 USD
4        5    Emp_5  Banglore   68611   802.47 USD
..     ...      ...       ...     ...          ...
95      96   Emp_96  Banglore   60006   701.82 USD
96      97   Emp_97     Noida   60635   709.18 USD
97      98   Emp_98   Gurgaon   51311   600.13 USD
98      99   Emp_99      Pune   89409  1045.72 USD
99     100  Emp_100   Gurgaon   92971  1087.38 USD

[100 rows x 5 columns]

In [16]:
data.to_dict()

{'Emp_id': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  10: 11,
  11: 12,
  12: 13,
  13: 14,
  14: 15,
  15: 16,
  16: 17,
  17: 18,
  18: 19,
  19: 20,
  20: 21,
  21: 22,
  22: 23,
  23: 24,
  24: 25,
  25: 26,
  26: 27,
  27: 28,
  28: 29,
  29: 30,
  30: 31,
  31: 32,
  32: 33,
  33: 34,
  34: 35,
  35: 36,
  36: 37,
  37: 38,
  38: 39,
  39: 40,
  40: 41,
  41: 42,
  42: 43,
  43: 44,
  44: 45,
  45: 46,
  46: 47,
  47: 48,
  48: 49,
  49: 50,
  50: 51,
  51: 52,
  52: 53,
  53: 54,
  54: 55,
  55: 56,
  56: 57,
  57: 58,
  58: 59,
  59: 60,
  60: 61,
  61: 62,
  62: 63,
  63: 64,
  64: 65,
  65: 66,
  66: 67,
  67: 68,
  68: 69,
  69: 70,
  70: 71,
  71: 72,
  72: 73,
  73: 74,
  74: 75,
  75: 76,
  76: 77,
  77: 78,
  78: 79,
  79: 80,
  80: 81,
  81: 82,
  82: 83,
  83: 84,
  84: 85,
  85: 86,
  86: 87,
  87: 88,
  88: 89,
  89: 90,
  90: 91,
  91: 92,
  92: 93,
  93: 94,
  94: 95,
  95: 96,
  96: 97,
  97: 98,
  98: 99,
  99: 100},
 'Name': {0: 'Emp_1',
  1: 'Emp_2',
  2: 'Emp_3',
  3: 'Emp_4',
  4: 'Emp_5',
  5: 'Emp_6',
  6: 'Emp_7',
  7: 'Emp_8',
  8: 'Emp_9',
  9: 'Emp_10',
  10: 'Emp_11',
  11: 'Emp_12',
  12: 'Emp_13',
  13: 'Emp_14',
  14: 'Emp_15',
  15: 'Emp_16',
  16: 'Emp_17',
  17: 'Emp_18',
  18: 'Emp_19',
  19: 'Emp_20',
  20: 'Emp_21',
  21: 'Emp_22',
  22: 'Emp_23',
  23: 'Emp_24',
  24: 'Emp_25',
  25: 'Emp_26',
  26: 'Emp_27',
  27: 'Emp_28',
  28: 'Emp_29',
  29: 'Emp_30',
  30: 'Emp_31',
  31: 'Emp_32',
  32: 'Emp_33',
  33: 'Emp_34',
  34: 'Emp_35',
  35: 'Emp_36',
  36: 'Emp_37',
  37: 'Emp_38',
  38: 'Emp_39',
  39: 'Emp_40',
  40: 'Emp_41',
  41: 'Emp_42',
  42: 'Emp_43',
  43: 'Emp_44',
  44: 'Emp_45',
  45: 'Emp_46',
  46: 'Emp_47',
  47: 'Emp_48',
  48: 'Emp_49',
  49: 'Emp_50',
  50: 'Emp_51',
  51: 'Emp_52',
  52: 'Emp_53',
  53: 'Emp_54',
  54: 'Emp_55',
  55: 'Emp_56',
  56: 'Emp_57',
  57: 'Emp_58',
  58: 'Emp_59',
  59: 'Emp_60',
  60: 'Emp_61',
  61: 'Emp_62',
  62: 'Emp_63',
  63: 'Emp_64',
  64: 'Emp_65',
  65: 'Emp_66',
  66: 'Emp_67',
  67: 'Emp_68',
  68: 'Emp_69',
  69: 'Emp_70',
  70: 'Emp_71',
  71: 'Emp_72',
  72: 'Emp_73',
  73: 'Emp_74',
  74: 'Emp_75',
  75: 'Emp_76',
  76: 'Emp_77',
  77: 'Emp_78',
  78: 'Emp_79',
  79: 'Emp_80',
  80: 'Emp_81',
  81: 'Emp_82',
  82: 'Emp_83',
  83: 'Emp_84',
  84: 'Emp_85',
  85: 'Emp_86',
  86: 'Emp_87',
  87: 'Emp_88',
  88: 'Emp_89',
  89: 'Emp_90',
  90: 'Emp_91',
  91: 'Emp_92',
  92: 'Emp_93',
  93: 'Emp_94',
  94: 'Emp_95',
  95: 'Emp_96',
  96: 'Emp_97',
  97: 'Emp_98',
  98: 'Emp_99',
  99: 'Emp_100'},
 'City': {0: 'Noida',
  1: 'Banglore',
  2: 'Noida',
  3: 'Pune',
  4: 'Banglore',
  5: 'Banglore',
  6: 'Banglore',
  7: 'Banglore',
  8: 'Gurgaon',
  9: 'Noida',
  10: 'Gurgaon',
  11: 'Noida',
  12: 'Gurgaon',
  13: 'Noida',
  14: 'Gurgaon',
  15: 'Pune',
  16: 'Pune',
  17: 'Gurgaon',
  18: 'Noida',
  19: 'Banglore',
  20: 'Gurgaon',
  21: 'Noida',
  22: 'Gurgaon',
  23: 'Banglore',
  24: 'Banglore',
  25: 'Banglore',
  26: 'Gurgaon',
  27: 'Banglore',
  28: 'Gurgaon',
  29: 'Gurgaon',
  30: 'Gurgaon',
  31: 'Pune',
  32: 'Pune',
  33: 'Noida',
  34: 'Gurgaon',
  35: 'Gurgaon',
  36: 'Noida',
  37: 'Gurgaon',
  38: 'Gurgaon',
  39: 'Pune',
  40: 'Gurgaon',
  41: 'Banglore',
  42: 'Noida',
  43: 'Pune',
  44: 'Noida',
  45: 'Banglore',
  46: 'Noida',
  47: 'Noida',
  48: 'Pune',
  49: 'Noida',
  50: 'Gurgaon',
  51: 'Noida',
  52: 'Gurgaon',
  53: 'Noida',
  54: 'Gurgaon',
  55: 'Gurgaon',
  56: 'Gurgaon',
  57: 'Gurgaon',
  58: 'Gurgaon',
  59: 'Noida',
  60: 'Gurgaon',
  61: 'Noida',
  62: 'Noida',
  63: 'Gurgaon',
  64: 'Noida',
  65: 'Gurgaon',
  66: 'Noida',
  67: 'Noida',
  68: 'Gurgaon',
  69: 'Gurgaon',
  70: 'Banglore',
  71: 'Banglore',
  72: 'Pune',
  73: 'Pune',
  74: 'Noida',
  75: 'Pune',
  76: 'Banglore',
  77: 'Noida',
  78: 'Pune',
  79: 'Banglore',
  80: 'Gurgaon',
  81: 'Gurgaon',
  82: 'Noida',
  83: 'Pune',
  84: 'Noida',
  85: 'Noida',
  86: 'Gurgaon',
  87: 'Noida',
  88: 'Gurgaon',
  89: 'Banglore',
  90: 'Pune',
  91: 'Pune',
  92: 'Pune',
  93: 'Gurgaon',
  94: 'Noida',
  95: 'Banglore',
  96: 'Noida',
  97: 'Gurgaon',
  98: 'Pune',
  99: 'Gurgaon'},
 'Salary': {0: 76252,
  1: 60315,
  2: 73672,
  3: 46501,
  4: 68611,
  5: 44646,
  6: 95408,
  7: 76171,
  8: 88999,
  9: 66920,
  10: 50618,
  11: 68936,
  12: 65217,
  13: 92541,
  14: 54983,
  15: 82394,
  16: 75880,
  17: 62554,
  18: 43908,
  19: 88460,
  20: 67993,
  21: 71302,
  22: 71056,
  23: 75523,
  24: 52524,
  25: 44710,
  26: 81768,
  27: 50894,
  28: 92523,
  29: 89967,
  30: 61738,
  31: 70196,
  32: 66026,
  33: 96846,
  34: 70137,
  35: 95851,
  36: 98538,
  37: 50073,
  38: 55501,
  39: 48539,
  40: 78222,
  41: 79663,
  42: 88075,
  43: 55560,
  44: 58527,
  45: 59409,
  46: 48400,
  47: 46042,
  48: 64984,
  49: 52329,
  50: 49728,
  51: 71335,
  52: 56694,
  53: 52683,
  54: 69958,
  55: 48805,
  56: 77990,
  57: 90425,
  58: 89058,
  59: 45004,
  60: 86314,
  61: 86583,
  62: 90083,
  63: 62304,
  64: 45905,
  65: 79358,
  66: 48382,
  67: 77912,
  68: 55457,
  69: 49003,
  70: 45849,
  71: 45944,
  72: 47144,
  73: 52826,
  74: 86643,
  75: 46014,
  76: 48192,
  77: 93787,
  78: 92844,
  79: 58371,
  80: 47726,
  81: 57981,
  82: 74060,
  83: 45896,
  84: 51840,
  85: 74826,
  86: 53125,
  87: 91586,
  88: 43883,
  89: 72727,
  90: 68734,
  91: 52235,
  92: 47001,
  93: 90450,
  94: 88315,
  95: 60006,
  96: 60635,
  97: 51311,
  98: 89409,
  99: 92971},
 'Salary_in_$': {0: '891.84 USD',
  1: '705.44 USD',
  2: '861.66 USD',
  3: '543.87 USD',
  4: '802.47 USD',
  5: '522.18 USD',
  6: '1115.88 USD',
  7: '890.89 USD',
  8: '1040.92 USD',
  9: '782.69 USD',
  10: '592.02 USD',
  11: '806.27 USD',
  12: '762.77 USD',
  13: '1082.35 USD',
  14: '643.08 USD',
  15: '963.67 USD',
  16: '887.49 USD',
  17: '731.63 USD',
  18: '513.54 USD',
  19: '1034.62 USD',
  20: '795.24 USD',
  21: '833.94 USD',
  22: '831.06 USD',
  23: '883.31 USD',
  24: '614.32 USD',
  25: '522.92 USD',
  26: '956.35 USD',
  27: '595.25 USD',
  28: '1082.14 USD',
  29: '1052.25 USD',
  30: '722.08 USD',
  31: '821.01 USD',
  32: '772.23 USD',
  33: '1132.7 USD',
  34: '820.32 USD',
  35: '1121.06 USD',
  36: '1152.49 USD',
  37: '585.65 USD',
  38: '649.13 USD',
  39: '567.71 USD',
  40: '914.88 USD',
  41: '931.73 USD',
  42: '1030.12 USD',
  43: '649.82 USD',
  44: '684.53 USD',
  45: '694.84 USD',
  46: '566.08 USD',
  47: '538.5 USD',
  48: '760.05 USD',
  49: '612.04 USD',
  50: '581.61 USD',
  51: '834.33 USD',
  52: '663.09 USD',
  53: '616.18 USD',
  54: '818.22 USD',
  55: '570.82 USD',
  56: '912.16 USD',
  57: '1057.6 USD',
  58: '1041.61 USD',
  59: '526.36 USD',
  60: '1009.52 USD',
  61: '1012.67 USD',
  62: '1053.6 USD',
  63: '728.7 USD',
  64: '536.9 USD',
  65: '928.16 USD',
  66: '565.87 USD',
  67: '911.25 USD',
  68: '648.62 USD',
  69: '573.13 USD',
  70: '536.25 USD',
  71: '537.36 USD',
  72: '551.39 USD',
  73: '617.85 USD',
  74: '1013.37 USD',
  75: '538.18 USD',
  76: '563.65 USD',
  77: '1096.92 USD',
  78: '1085.89 USD',
  79: '682.7 USD',
  80: '558.2 USD',
  81: '678.14 USD',
  82: '866.2 USD',
  83: '536.8 USD',
  84: '606.32 USD',
  85: '875.16 USD',
  86: '621.35 USD',
  87: '1071.18 USD',
  88: '513.25 USD',
  89: '850.61 USD',
  90: '803.91 USD',
  91: '610.94 USD',
  92: '549.72 USD',
  93: '1057.89 USD',
  94: '1032.92 USD',
  95: '701.82 USD',
  96: '709.18 USD',
  97: '600.13 USD',
  98: '1045.72 USD',
  99: '1087.38 USD'}}

In [17]:
data.to_json()

'{"Emp_id":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9,"9":10,"10":11,"11":12,"12":13,"13":14,"14":15,"15":16,"16":17,"17":18,"18":19,"19":20,"20":21,"21":22,"22":23,"23":24,"24":25,"25":26,"26":27,"27":28,"28":29,"29":30,"30":31,"31":32,"32":33,"33":34,"34":35,"35":36,"36":37,"37":38,"38":39,"39":40,"40":41,"41":42,"42":43,"43":44,"44":45,"45":46,"46":47,"47":48,"48":49,"49":50,"50":51,"51":52,"52":53,"53":54,"54":55,"55":56,"56":57,"57":58,"58":59,"59":60,"60":61,"61":62,"62":63,"63":64,"64":65,"65":66,"66":67,"67":68,"68":69,"69":70,"70":71,"71":72,"72":73,"73":74,"74":75,"75":76,"76":77,"77":78,"78":79,"79":80,"80":81,"81":82,"82":83,"83":84,"84":85,"85":86,"86":87,"87":88,"88":89,"89":90,"90":91,"91":92,"92":93,"93":94,"94":95,"95":96,"96":97,"97":98,"98":99,"99":100},"Name":{"0":"Emp_1","1":"Emp_2","2":"Emp_3","3":"Emp_4","4":"Emp_5","5":"Emp_6","6":"Emp_7","7":"Emp_8","8":"Emp_9","9":"Emp_10","10":"Emp_11","11":"Emp_12","12":"Emp_13","13":"Emp_14","14":"Emp_15","15":"Emp_16","16":"Emp_17","17":"Emp_18","18":"Emp_19","19":"Emp_20","20":"Emp_21","21":"Emp_22","22":"Emp_23","23":"Emp_24","24":"Emp_25","25":"Emp_26","26":"Emp_27","27":"Emp_28","28":"Emp_29","29":"Emp_30","30":"Emp_31","31":"Emp_32","32":"Emp_33","33":"Emp_34","34":"Emp_35","35":"Emp_36","36":"Emp_37","37":"Emp_38","38":"Emp_39","39":"Emp_40","40":"Emp_41","41":"Emp_42","42":"Emp_43","43":"Emp_44","44":"Emp_45","45":"Emp_46","46":"Emp_47","47":"Emp_48","48":"Emp_49","49":"Emp_50","50":"Emp_51","51":"Emp_52","52":"Emp_53","53":"Emp_54","54":"Emp_55","55":"Emp_56","56":"Emp_57","57":"Emp_58","58":"Emp_59","59":"Emp_60","60":"Emp_61","61":"Emp_62","62":"Emp_63","63":"Emp_64","64":"Emp_65","65":"Emp_66","66":"Emp_67","67":"Emp_68","68":"Emp_69","69":"Emp_70","70":"Emp_71","71":"Emp_72","72":"Emp_73","73":"Emp_74","74":"Emp_75","75":"Emp_76","76":"Emp_77","77":"Emp_78","78":"Emp_79","79":"Emp_80","80":"Emp_81","81":"Emp_82","82":"Emp_83","83":"Emp_84","84":"Emp_85","85":"Emp_86","86":"Emp_87","87":"Emp_88","88":"Emp_89","89":"Emp_90","90":"Emp_91","91":"Emp_92","92":"Emp_93","93":"Emp_94","94":"Emp_95","95":"Emp_96","96":"Emp_97","97":"Emp_98","98":"Emp_99","99":"Emp_100"},"City":{"0":"Noida","1":"Banglore","2":"Noida","3":"Pune","4":"Banglore","5":"Banglore","6":"Banglore","7":"Banglore","8":"Gurgaon","9":"Noida","10":"Gurgaon","11":"Noida","12":"Gurgaon","13":"Noida","14":"Gurgaon","15":"Pune","16":"Pune","17":"Gurgaon","18":"Noida","19":"Banglore","20":"Gurgaon","21":"Noida","22":"Gurgaon","23":"Banglore","24":"Banglore","25":"Banglore","26":"Gurgaon","27":"Banglore","28":"Gurgaon","29":"Gurgaon","30":"Gurgaon","31":"Pune","32":"Pune","33":"Noida","34":"Gurgaon","35":"Gurgaon","36":"Noida","37":"Gurgaon","38":"Gurgaon","39":"Pune","40":"Gurgaon","41":"Banglore","42":"Noida","43":"Pune","44":"Noida","45":"Banglore","46":"Noida","47":"Noida","48":"Pune","49":"Noida","50":"Gurgaon","51":"Noida","52":"Gurgaon","53":"Noida","54":"Gurgaon","55":"Gurgaon","56":"Gurgaon","57":"Gurgaon","58":"Gurgaon","59":"Noida","60":"Gurgaon","61":"Noida","62":"Noida","63":"Gurgaon","64":"Noida","65":"Gurgaon","66":"Noida","67":"Noida","68":"Gurgaon","69":"Gurgaon","70":"Banglore","71":"Banglore","72":"Pune","73":"Pune","74":"Noida","75":"Pune","76":"Banglore","77":"Noida","78":"Pune","79":"Banglore","80":"Gurgaon","81":"Gurgaon","82":"Noida","83":"Pune","84":"Noida","85":"Noida","86":"Gurgaon","87":"Noida","88":"Gurgaon","89":"Banglore","90":"Pune","91":"Pune","92":"Pune","93":"Gurgaon","94":"Noida","95":"Banglore","96":"Noida","97":"Gurgaon","98":"Pune","99":"Gurgaon"},"Salary":{"0":76252,"1":60315,"2":73672,"3":46501,"4":68611,"5":44646,"6":95408,"7":76171,"8":88999,"9":66920,"10":50618,"11":68936,"12":65217,"13":92541,"14":54983,"15":82394,"16":75880,"17":62554,"18":43908,"19":88460,"20":67993,"21":71302,"22":71056,"23":75523,"24":52524,"25":44710,"26":81768,"27":50894,"28":92523,"29":89967,"30":61738,"31":70196,"32":66026,"33":96846,"34":70137,"35":95851,"36":98538,"37":50073,"38":55501,"39":48539,"40":78222,"41":79663,"42":88075,"43":55560,"44":58527,"45":59409,"46":48400,"47":46042,"48":64984,"49":52329,"50":49728,"51":71335,"52":56694,"53":52683,"54":69958,"55":48805,"56":77990,"57":90425,"58":89058,"59":45004,"60":86314,"61":86583,"62":90083,"63":62304,"64":45905,"65":79358,"66":48382,"67":77912,"68":55457,"69":49003,"70":45849,"71":45944,"72":47144,"73":52826,"74":86643,"75":46014,"76":48192,"77":93787,"78":92844,"79":58371,"80":47726,"81":57981,"82":74060,"83":45896,"84":51840,"85":74826,"86":53125,"87":91586,"88":43883,"89":72727,"90":68734,"91":52235,"92":47001,"93":90450,"94":88315,"95":60006,"96":60635,"97":51311,"98":89409,"99":92971},"Salary_in_$":{"0":"891.84 USD","1":"705.44 USD","2":"861.66 USD","3":"543.87 USD","4":"802.47 USD","5":"522.18 USD","6":"1115.88 USD","7":"890.89 USD","8":"1040.92 USD","9":"782.69 USD","10":"592.02 USD","11":"806.27 USD","12":"762.77 USD","13":"1082.35 USD","14":"643.08 USD","15":"963.67 USD","16":"887.49 USD","17":"731.63 USD","18":"513.54 USD","19":"1034.62 USD","20":"795.24 USD","21":"833.94 USD","22":"831.06 USD","23":"883.31 USD","24":"614.32 USD","25":"522.92 USD","26":"956.35 USD","27":"595.25 USD","28":"1082.14 USD","29":"1052.25 USD","30":"722.08 USD","31":"821.01 USD","32":"772.23 USD","33":"1132.7 USD","34":"820.32 USD","35":"1121.06 USD","36":"1152.49 USD","37":"585.65 USD","38":"649.13 USD","39":"567.71 USD","40":"914.88 USD","41":"931.73 USD","42":"1030.12 USD","43":"649.82 USD","44":"684.53 USD","45":"694.84 USD","46":"566.08 USD","47":"538.5 USD","48":"760.05 USD","49":"612.04 USD","50":"581.61 USD","51":"834.33 USD","52":"663.09 USD","53":"616.18 USD","54":"818.22 USD","55":"570.82 USD","56":"912.16 USD","57":"1057.6 USD","58":"1041.61 USD","59":"526.36 USD","60":"1009.52 USD","61":"1012.67 USD","62":"1053.6 USD","63":"728.7 USD","64":"536.9 USD","65":"928.16 USD","66":"565.87 USD","67":"911.25 USD","68":"648.62 USD","69":"573.13 USD","70":"536.25 USD","71":"537.36 USD","72":"551.39 USD","73":"617.85 USD","74":"1013.37 USD","75":"538.18 USD","76":"563.65 USD","77":"1096.92 USD","78":"1085.89 USD","79":"682.7 USD","80":"558.2 USD","81":"678.14 USD","82":"866.2 USD","83":"536.8 USD","84":"606.32 USD","85":"875.16 USD","86":"621.35 USD","87":"1071.18 USD","88":"513.25 USD","89":"850.61 USD","90":"803.91 USD","91":"610.94 USD","92":"549.72 USD","93":"1057.89 USD","94":"1032.92 USD","95":"701.82 USD","96":"709.18 USD","97":"600.13 USD","98":"1045.72 USD","99":"1087.38 USD"}}'

In [19]:
data.to_csv("Final_data.csv",index=False)