In [1]:
import numpy as np
import matplotlib.pyplot as ptl
import pandas as pd
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df=sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Quantiles

In [5]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
df.describe(percentiles=[0.2,0.4,0.6,0.8])

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
20%        5.000000     2.700000      1.500000     0.200000
40%        5.600000     3.000000      3.900000     1.160000
50%        5.800000     3.000000      4.350000     1.300000
60%        6.100000     3.100000      4.640000     1.500000
80%        6.520000     3.400000      5.320000     1.900000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
df.describe(percentiles=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1])

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
10%        4.800000     2.500000      1.400000     0.200000
20%        5.000000     2.700000      1.500000     0.200000
30%        5.270000     2.800000      1.700000     0.400000
40%        5.600000     3.000000      3.900000     1.160000
50%        5.800000     3.000000      4.350000     1.300000
60%        6.100000     3.100000      4.640000     1.500000
70%        6.300000     3.200000      5.000000     1.800000
80%        6.520000     3.400000      5.320000     1.900000
90%        6.900000     3.610000      5.800000     2.200000
100%       7.900000     4.400000      6.900000     2.500000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [10]:
df.drop("species",axis=1,inplace=True)

In [11]:
df.quantile(0.25)

sepal_length    5.1
sepal_width     2.8
petal_length    1.6
petal_width     0.3
Name: 0.25, dtype: float64

In [12]:
df["sepal_length"].quantile(0.25)

5.1

# Sampling techniques

In [16]:
df=sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

__Simple Random Sampling__

In [22]:
n=10
sample_df=df.sample(n,random_state=22)#through this we fixed it,means whenever we call it there is always same sample of data.
print("Sample random sampling")
sample_df

Sample random sampling

     sepal_length  sepal_width  petal_length  petal_width     species
10            5.4          3.7           1.5          0.2      setosa
115           6.4          3.2           5.3          2.3   virginica
54            6.5          2.8           4.6          1.5  versicolor
146           6.3          2.5           5.0          1.9   virginica
63            6.1          2.9           4.7          1.4  versicolor
76            6.8          2.8           4.8          1.4  versicolor
86            6.7          3.1           4.7          1.5  versicolor
138           6.0          3.0           4.8          1.8   virginica
64            5.6          2.9           3.6          1.3  versicolor
35            5.0          3.2           1.2          0.2      setosa

# Systematic sampling
__It follow certain rule__

In [23]:
n=15
new_df=df.iloc[::n]
new_df

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
15            5.7          4.4           1.5          0.4      setosa
30            4.8          3.1           1.6          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
60            5.0          2.0           3.5          1.0  versicolor
75            6.6          3.0           4.4          1.4  versicolor
90            5.5          2.6           4.4          1.2  versicolor
105           7.6          3.0           6.6          2.1   virginica
120           6.9          3.2           5.7          2.3   virginica
135           7.7          3.0           6.1          2.3   virginica

# Stratified sampling
- Divide the data into groups  based on specific column then select randomly from it

In [24]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [27]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [29]:
stratified=df.groupby("species").apply(lambda x:x.sample(min(len(x),5)))
stratified

                sepal_length  sepal_width  petal_length  petal_width  \
species
setosa     33            5.5          4.2           1.4          0.2
           20            5.4          3.4           1.7          0.2
           17            5.1          3.5           1.4          0.3
           15            5.7          4.4           1.5          0.4
           7             5.0          3.4           1.5          0.2
versicolor 88            5.6          3.0           4.1          1.3
           82            5.8          2.7           3.9          1.2
           75            6.6          3.0           4.4          1.4
           69            5.6          2.5           3.9          1.1
           70            5.9          3.2           4.8          1.8
virginica  116           6.5          3.0           5.5          1.8
           118           7.7          2.6           6.9          2.3
           130           7.4          2.8           6.1          1.9
           100           6.3          3.3           6.0          2.5
           121           5.6          2.8           4.9          2.0

                   species
species
setosa     33       setosa
           20       setosa
           17       setosa
           15       setosa
           7        setosa
versicolor 88   versicolor
           82   versicolor
           75   versicolor
           69   versicolor
           70   versicolor
virginica  116   virginica
           118   virginica
           130   virginica
           100   virginica
           121   virginica

In [33]:
stratified=df.groupby("species", group_keys=False).apply(lambda x:x.sample(min(len(x),3)))
stratified

     sepal_length  sepal_width  petal_length  petal_width     species
13            4.3          3.0           1.1          0.1      setosa
43            5.0          3.5           1.6          0.6      setosa
12            4.8          3.0           1.4          0.1      setosa
60            5.0          2.0           3.5          1.0  versicolor
95            5.7          3.0           4.2          1.2  versicolor
90            5.5          2.6           4.4          1.2  versicolor
103           6.3          2.9           5.6          1.8   virginica
124           6.7          3.3           5.7          2.1   virginica
116           6.5          3.0           5.5          1.8   virginica

# Cluster Sampling

In [35]:
clusters= df["species"].unique()
clusters

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [41]:
df=pd.concat([df[df["species"]==i].sample(2) for i in np.random.choice(clusters,size=2,replace=False)]

SyntaxError: incomplete input (1838634366.py, line 1)

In [47]:
s=df[df["species"]=="versicolor"]
s

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor